name: Deploy_DEV
on:
  push: 
    branches: 
      - deploy

env:
  #KUBECONFIG: ${{ secrets.KUBECONFIG }}
  APP_NAME: tagion-home
  DEV_PROJECT_NAME: dev-tagion-home



jobs:
  deploy:
    name: Build Image
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: tagion-home
        IMAGE_TAG: ${{ github.sha }}
      run: |
        npm install --legacy-peer-deps
        npm run build
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Update kube config
      run: |
        aws eks update-kubeconfig --name eks --region ${{ secrets.AWS_DEFAULT_REGION }}
        kubectl get ing

    - name: Deploy to EKS
      run: |
        kubectl delete deploy $TEST_PROJECT_NAME || kubectl get deploy
        envsubst < k8s/dev_deployment.yml | kubectl apply -f -
