name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

env:
  APP_NAME: tagion-home
  PROD_PROJECT_NAME: prod-tagion-home
  GATSBY_ENV: ${{ secrets.GATSBY_ENV }}
  GATSBY_GOOGLE_ANALYTICS_ID: ${{ secrets.GATSBY_GOOGLE_ANALYTICS_ID }}
  GATSBY_MAIL_SERVICE_ENDPOINT: ${{ vars.GATSBY_MAIL_SERVICE_ENDPOINT }}

jobs:
  deploy:
    name: Deploy to GitHub Pages

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: create .env file
        run: |
          echo ${{ env.GATSBY_ENV }} > .env
          echo ${{ env.GATSBY_GOOGLE_ANALYTICS_ID }} >> .env
          echo ${{ env.GATSBY_MAIL_SERVICE_ENDPOINT }} >> .env

      - name: Install dependencies
        run: npm install --legacy-peer-deps 
  
      - name: build site
        run: |
          npm run build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: "public/"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
