name: Deploy_PROD
on:
  push: 
    branches: 
      - master
      - main

env:
  APP_NAME: tagion-home
  PROD_PROJECT_NAME: prod-tagion-home
  GATSBY_ENV: ${{ secrets.GATSBY_ENV }}
  GATSBY_GOOGLE_ANALYTICS_ID: ${{ secrets.GATSBY_GOOGLE_ANALYTICS_ID }}
  GATSBY_MAIL_SERVICE_ENDPOINT: ${{ vars.GATSBY_MAIL_SERVICE_ENDPOINT }}

jobs:
  deploy:
    name: Build Image
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: tagion-home
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo ${{ env.GATSBY_ENV }} > .env
        echo ${{ env.GATSBY_GOOGLE_ANALYTICS_ID }} >> .env
        echo ${{ env.GATSBY_MAIL_SERVICE_ENDPOINT }} >> .env
        npm install --legacy-peer-deps
        npm run build
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push -a $ECR_REGISTRY/$ECR_REPOSITORY

    - name: Update kube config
      run: |
        aws eks update-kubeconfig --name eks --region ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Deploy to EKS
      run: |
        kubectl delete deploy $PROD_PROJECT_NAME || echo "old deploy deleted"
        kubectl apply -f k8s/prod_deployment.yml
