export enum Colors {
  MAIN_DARK = "#121113",
  MAIN_WHITE = "#FFFFFF",
  GRADIENT_SPOT_GREEN = "#55FFA6", // Phito Green
  GRADIENT_SPOT_PURPLE = "#3040CF",
  GRADIENT_SPOT_IONIC_MINT = "#00B6C1",
  GRADIENT_SPOT_OZONE_BLUE = "#4F36E3",
  GRADIENT_SPOT_SPACE_BLUE = "#3F0B81",
}
